In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

In [10]:
def csv_downloader(URL:str, name:str, path:str)->pd.DataFrame:
    df = pd.read_csv(URL)
    df.to_csv(f'{path}/{name}.csv', index = False)
    print(f'The {name}.csv was successfully stored in {path}')
    return df

In [5]:
df.head()

           customer_id  order_date  revenue
0  Mr. Brion Stark Sr.  2004-12-20       32
1       Ethyl Botsford  2005-05-02       36
2       Hosteen Jacobi  2004-03-06      116
3        Mr. Edw Frami  2006-03-15       99
4          Josef Lemke  2006-08-14       76

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4906 entries, 0 to 4905
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  4906 non-null   str
 1   order_date   4906 non-null   str
 2   revenue      4906 non-null   int64
dtypes: int64(1), str(2)
memory usage: 237.5 KB

In [7]:
df.describe()

           revenue
count  4906.000000
mean     94.610273
std      57.827010
min      10.000000
25%      45.000000
50%      81.000000
75%     137.000000
max     219.000000

In [8]:
df.columns

Index(['customer_id', 'order_date', 'revenue'], dtype='str')

In [11]:
URL = 'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/rfm/orders.csv'
df = pd.read_csv(URL)

In [12]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

pd.set_option('display.max_columns', None)
px.defaults.template = "plotly_white"

In [1]:
orders = pd.read_csv('../data/rfm/orders.csv', parse_dates=['order_date'])
orders.head()

NameError: name 'pd' is not defined

In [2]:
fig = px.histogram(
    orders,
    x='revenue',
    nbins=30,
    title='Histogram of Revenue'
)

fig.update_layout(
    xaxis_title='Revenue',
    yaxis_title='Count'
)

fig.show()

NameError: name 'px' is not defined